cinivy/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource

movie_resource = MovieResource()
# movie_resource.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls))
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail')
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

# Create your models here.

class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name ='movies'
        excludes = ['date_created']

movies/models.py
from django.utils import timezone
from django.db import models

# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie

# Create your views here.

def index (request):
    movies = Movie.objects.all()
    return render (request, 'movies/index.html', {'movies' : movies})
    return HttpResponse("Holla ")
  

def detail (request, movie_id):

    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})
    

movies/templates/movies/detail.html
{% extends 'base.html' %}


{% block content %}

<dl>
    <dt>Title</dt>
    <dd>{{ movie.title }}</dd>
    <dt>Genre</dt>
    <dd>{{ movie.genre }}</dd>
    <dt>Stock</dt>
    <dd>{{ movie.number_in_stock }}</dd>
</dl>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% block content %}

    <table class="table table-bordered table-hover">
        
        <thead>
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Stock</th>
                <th>Daily Rate</th>
            </tr>
            <tbody>
                {% for movie in movies %}
                
                <tr>
                    <td>
                    <!-- <a href="/movies/{{ movie.id}}"> {{ movie.title }}    </a> -->
                      <a href="{% url 'movies:detail' movie.id %}"> {{ movie.title }}    </a>
                  

                    </td>
                    <td>{{ movie.genre }}</td>
                    <td>{{ movie.number_in_stock }}</td>
                    <td>{{ movie.daily_rate }}</td>
                    
                </tr>

                {% endfor %}
            </tbody>
        </thead>
    </table>

{% endblock %}

    
</body>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cinivy By KayMohh</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Cinivy By KayMohh</a>
        </div>
      </nav>
      
    <main class="container">

        
        {% block content %}
        
        {% endblock %}
    </main>


    
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>